### ISSUE TITLE
TODO: More Shortis

### ISSUE THREAD

**Issue by tonyspiro** [tonyspiro/shorti#2]
- [ ] **upper** - to upper case
- [ ] **line-through** - textDecoration: 'line-through'
- [x] **border-1-solid-ccc** - multiple border value
- [x] **border-[top,right,bottom,left]-1-solid-ccc** - multiple border value
- [ ] **p-5-0-10** - multiple padding/margin value
- [x] **border-none** - no border
- [ ] **hover-[shorti]** - hover stuff
